# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
target 'uTanks' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Socket.IO-Client-Swift', '~> 13.1.0'

  # Pods for SocketIOExample

end
